### ISSUE TITLE
Settings keys are not case consistent

### ISSUE THREAD

**Issue by flavio** [kubewarden/verify-image-signatures#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some of the settings are using snake case (like `keyless_prefix`) while others are camel case (like `pubKeys`).

Everything should stay consistent.

I propose to use camel case because this is what the kubernetes world uses.

### Expected Behavior

All the settings keys use the same naming convention

**Comment by viccuad** [comment]
It would also be nice to converge to the [verificationConfig of PolicyServer](https://docs.kubewarden.io/operator-manual/verification-config) (or at least, don't diverge).

**Comment by flavio** [comment]
which means `camelCase`. That's fine with me
