### ISSUE TITLE
settings validations: implement certificate chain verification

### ISSUE THREAD

**Issue by flavio** [kubewarden/verify-image-signatures#44]
When using the new `Certificate` option, the `validate_settings` should ensure the certificate can be verified using the optional `certificate_chain` provided by the user.

See https://github.com/kubewarden/verify-image-signatures/blob/b6a1c64abfcb1f78fd20937e3b30d97ea65576b8/src/settings.rs#L108-L109

This is part of https://github.com/kubewarden/verify-image-signatures/issues/39

**Comment by flavio** [comment]
This depends on https://github.com/kubewarden/policy-evaluator/issues/200

**Comment by viccuad** [comment]
https://github.com/kubewarden/verify-image-signatures/pull/47 implements it, but missing e2e tests in a new PR.
