### ISSUE TITLE
Feature Request: missing question.yml file

### ISSUE THREAD

**Issue by jvanz** [kubewarden/verify-image-signatures#57]
### Is your feature request related to a problem?

The policy has settings and in order to be able to properly show it in the UI we need the question.yml file.

### Solution you'd like

Add the question.yml used by the UI.

### Anything else?

Related to https://github.com/kubewarden/ui/issues/207

**Comment by jvanz** [comment]
FYI @jordojordo

**Comment by flavio** [comment]
I've added the file
